#!/bin/sh
# SL8541E GNSS Stock Revert Script (Standalone)
# Restores original factory configs and cleans all caches.

echo "--- Starting GNSS Stock Revert ---"

# 1. Root Check
if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] You must run this as root (su)!"
    exit 1
fi

# 2. Remount filesystems
echo "[STEP] Remounting filesystems..."
mount -o remount,rw /vendor 2>/dev/null
mount -o remount,rw /data 2>/dev/null
mount -o remount,rw /system 2>/dev/null

# 3. Define Embedded Contents
CONFIG_CONTENT='<?xml version="1.0" encoding="utf-8"?>
<GNSS>
	<PROPERTY NAME="CHIP-MODULE" VALUE="GREENEYE2"/>
	<PROPERTY NAME="GPS-IMG-MODE" VALUE="GNSSMODEM"/>
	<PROPERTY NAME="GE2-VERSION" VALUE=""/>
	<PROPERTY NAME="SPREADORBIT-ENABLE" VALUE="TRUE"/>
	<PROPERTY NAME="CP-MODE" VALUE="101"/>
	<PROPERTY NAME="CHIP-ID" VALUE="SP12"/>
	<PROPERTY NAME="OUTPUT-PROTOCOL" VALUE="0011"/>
	<PROPERTY NAME="LOG-ENABLE" VALUE="FALSE"/>
	<PROPERTY NAME="UART-NAME" VALUE="/dev/ttyS3"/>
	<PROPERTY NAME="UART-SPEED" VALUE="3000000"/>
	<PROPERTY NAME="STTY-NAME" VALUE="/dev/sttygnss0"/>
	<PROPERTY NAME="DEBUG-ENABLE" VALUE="TRUE"/>
	<PROPERTY NAME="POST-ENABLE" VALUE="FALSE"/>
	<PROPERTY NAME="APWDG-ENABLE" VALUE="TRUE"/>
	<PROPERTY NAME="REALEPH-ENABLE" VALUE="FALSE"/>
	<PROPERTY NAME="SLEEP-ENABLE" VALUE="TRUE"/>
	<PROPERTY NAME="SLEEP-TIMER" VALUE="300"/>
	<PROPERTY NAME="STOP-TIMER" VALUE="1"/>
	<PROPERTY NAME="CMCC-ENABLE" VALUE="TRUE"/>
	<PROPERTY NAME="TSX-ENABLE" VALUE="FALSE"/>
	<PROPERTY NAME="RF-TOOL" VALUE="FALSE"/>
	<PROPERTY NAME="SUPL-PATH" VALUE="/vendor/etc/supl.xml"/>
	<PROPERTY NAME="NOKIA-EE" VALUE="FALSE"/>
	<PROPERTY NAME="FLOAT-CN0" VALUE="FALSE"/>
	<PROPERTY NAME="BASEBAND-MODE" VALUE="FALSE"/>
	<PROPERTY NAME="MEASURE-REPORT" VALUE="TRUE"/>
	<PROPERTY NAME="PRODUCT_PLATFORM" VALUE="0"/>
</GNSS>
'

SUPL_CONTENT='<?xml version="1.0" encoding="utf-8"?>
<SPRDGNSS>
	<COMM>
		<PROTOCOL NAME="RX_SUPL_PROTOCOL" TYPE="SUPL" INTERFACE="DUMMY2">
		  <PROPERTY NAME="ENABLE" VALUE="TRUE"/>
		  <PROPERTY NAME="SERVER-ADDRESS" VALUE="unisoc.supl.qxwz.com"/>
		  <PROPERTY NAME="SERVER-PORT" VALUE="7275"/>
		  <PROPERTY NAME="HLP-ENABLE" VALUE="FALSE"/>
		  <PROPERTY NAME="HLP-ADDRESS" VALUE=""/>
		  <PROPERTY NAME="HLP-PORT" VALUE=""/>
		  <PROPERTY NAME="SUPL-MODE" VALUE="msb"/>
		  <PROPERTY NAME="VERSION" VALUE="SUPL_15.5.2"/>
		  <PROPERTY NAME="SUPL-VERSION" VALUE="v2.0.0"/>
		  <PROPERTY NAME="LOG-ENABLE" VALUE="TRUE"/>		
		  <PROPERTY NAME="RESET-ENABLE" VALUE="FALSE"/>
		  <PROPERTY NAME="UDP-ENABLE" VALUE="FALSE"/>
		  <PROPERTY NAME="CONTROL-PLANE" VALUE="FALSE"/>
		  <PROPERTY NAME="MIN-PERFORMANCE" VALUE="FALSE"/>
		  <PROPERTY NAME="MPM" VALUE="LOCATION"/>
		  <PROPERTY NAME="ExtAddr Enable" VALUE="FALSE"/>
		  <PROPERTY NAME="EXTERNAL-ADDRESS" VALUE="123456"/>
		  <PROPERTY NAME="MlcNum Enable" VALUE="FALSE"/>
		  <PROPERTY NAME="MLC-NUMBER" VALUE="123456"/>
		  <PROPERTY NAME="CP-AUTORESET" VALUE="TRUE"/>
		  <PROPERTY NAME="CER-VERIFY" VALUE="FALSE"/>
		  <PROPERTY NAME="SUPL-CER" VALUE="/data/gnss/supl/suplrootca.pem"/>
		  <PROPERTY NAME="CELL-ID-GSM-MCC" VALUE="460"/>
		  <PROPERTY NAME="CELL-ID-GSM-MNC" VALUE="1"/>
		  <PROPERTY NAME="CELL-ID-GSM-LAC" VALUE="6340"/>
		  <PROPERTY NAME="CELL-ID-GSM-CI" VALUE="9457"/>
		  <PROPERTY NAME="TLS-ENABLE" VALUE="TRUE"/>
		  <PROPERTY NAME="SETID" VALUE="IMSI"/>
		  <PROPERTY NAME="ACCURACY-UNIT" VALUE="METER"/>
		  <PROPERTY NAME="HORIZON-ACCURACY" VALUE="25"/>
		  <PROPERTY NAME="VERTICAL-ACCURACY" VALUE="10"/>
		  <PROPERTY NAME="LOC-AGE" VALUE="0"/>
		  <PROPERTY NAME="DELAY" VALUE="0"/>
		  <PROPERTY NAME="LAB-IOT" VALUE="FALSE"/>
		  <PROPERTY NAME="ECID-ENABLE" VALUE="FALSE"/>
		  <PROPERTY NAME="LOCAL-MSISDN" VALUE="0"/>
		  <PROPERTY NAME="3RD-MSISDN" VALUE="0"/>
		  <PROPERTY NAME="TRIGGER-START" VALUE="FALSE"/>
		  <PROPERTY NAME="TRIGGER-TYPE" VALUE="AREA"/>
		  <PROPERTY NAME="PERIODIC-MIN-INTERVAL" VALUE="60"/>
		  <PROPERTY NAME="PERIODIC-START-TIME" VALUE="30"/>
		  <PROPERTY NAME="PERIODIC-STOP-TIME" VALUE="240"/>
		  <PROPERTY NAME="PERIODIC-POSMETHOD" VALUE="BASE"/>
		  <PROPERTY NAME="AREA-POSMETHOD" VALUE="BASE"/>
		  <PROPERTY NAME="AREA-TYPE" VALUE="INSIDE"/>
		  <PROPERTY NAME="GEOGRAPHIC" VALUE="CIRCULAR"/>
		  <PROPERTY NAME="GEORADIUS" VALUE="1000"/>
		  <PROPERTY NAME="GEO-LAT" VALUE="31.6658"/>
		  <PROPERTY NAME="GEO-LON" VALUE="121.4564"/>
		  <PROPERTY NAME="GEO-TRIGGER" VALUE="FALSE"/>
		  <PROPERTY NAME="SIGN" VALUE="NORTH"/>
		  <PROPERTY NAME="AREA-MIN-INTERVAL" VALUE="60"/>
		  <PROPERTY NAME="MAX-NUM" VALUE="5"/>
		  <PROPERTY NAME="AREA-START-TIME" VALUE="30"/>
		  <PROPERTY NAME="AREA-STOP-TIME" VALUE="240"/>
		  <PROPERTY NAME="NI-ENABLE" VALUE="TRUE"/>
		  <PROPERTY NAME="EM-NOTIFY" VALUE="FALSE"/>
		  <PROPERTY NAME="ROAMING-ENABLE" VALUE="TRUE"/>
		  <PROPERTY NAME="SUPLLOG-SAVE" VALUE="FALSE"/>
		  <PROPERTY NAME="NOTIFY-TIMEOUT" VALUE="8"/>
		  <PROPERTY NAME="VERIFY-TIMEOUT" VALUE="8"/>
		  <PROPERTY NAME="NI-TEST" VALUE="NOTIFIONLY"/>
		  <PROPERTY NAME="HASH-ALGO" VALUE="AUTO"/>
		  <PROPERTY NAME="REAL-TIME" VALUE="TRUE"/>
		  <PROPERTY NAME="QUASIREAL-TIME" VALUE="TRUE"/>
		  <PROPERTY NAME="BATCH" VALUE="TRUE"/>
		  <PROPERTY NAME="MAXNUM-POS" VALUE="60"/>
		  <PROPERTY NAME="MAXNUM-MSR" VALUE="60"/>
		  <PROPERTY NAME="PERIODIC-MININT" VALUE="10"/>
		  <PROPERTY NAME="PERIODIC-MAXINT" VALUE="60"/>
		</PROTOCOL>
	</COMM>
</SPRDGNSS>
'

# 4. Restore config.xml
echo "[STEP] Restoring config.xml..."
echo "$CONFIG_CONTENT" > /vendor/etc/config.xml
echo "[OK] config.xml restored (Embedded)."

# 5. Restore supl.xml
echo "[STEP] Restoring supl.xml..."
echo "$SUPL_CONTENT" > /vendor/etc/supl.xml
echo "$SUPL_CONTENT" > /data/gnss/supl/supl.xml
echo "[OK] supl.xml restored (Embedded)."

# 6. Deep Cleanup
echo "[STEP] Purging GNSS caches..."
rm -rf /data/gnss/lte/*
rm -rf /data/gnss/supl/*.xml
rm -rf /data/gnss/log/*

# 7. SELinux restoration
echo "[STEP] Restoring contexts..."
restorecon -R /vendor/etc/config.xml 2>/dev/null
restorecon -R /vendor/etc/supl.xml 2>/dev/null
restorecon -R /data/gnss/supl/ 2>/dev/null

# Log On-Device
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Applied STOCK Revert" >> /data/gnss/fix_history.log

echo "--- Original Vendor Configs Restored. Please REBOOT ---"
