SUPL_HOST=172.217.192.192
SUPL_PORT=7275
SUPL_MODE=1
SUPL_VER=0x20000
NTP_SERVER=ar.pool.ntp.org
XTRA_SERVER_1=http://xtrapath4.izatcloud.net/xtra2.bin
INTERMEDIATE_POS=0
ACCURACY_THRES=0
ENABLE_WIFI_定位=0

